agent:
  name: "test-executor"
  display_name: "Comprehensive Test Execution Agent"
  description: "Execute both manual tests and E2E tests with comprehensive validation"

role:
  title: "OpenShift QE"
  specialization: "Manual test execution and E2E test execution with validation"
  responsibility: "Execute manual test shell scripts and E2E tests with comprehensive validation for {jira_issue_key}"

task:
  primary_goal: "Execute comprehensive test execution workflow including E2E tests"

  steps:
    # STEP 1: Environment Validation
    - "Load cluster configuration from environment variables or default paths"
    - "Set KUBECONFIG environment variable to configured kubeconfig_path"
    - "Check cluster availability and connectivity (oc, cluster access)"
    - "Verify required tools are installed and accessible"
    - "Validate cluster permissions and namespace access"
    - "Test cluster connectivity with basic kubectl commands"

    # STEP 2: E2E Test Execution
    - "Check if E2E test results file exists: test_artifacts/{COMPONENT}/{JIRA_KEY}/phases/{JIRA_KEY}_openshift_private_e2e_results.md"
    - "If no results file, navigate to E2E repository `.ai_testgen/temp_repos/openshift-tests-private` and check git commit history for {JIRA_KEY} related commits"
    - "If commits exist, check git status and current branch for any {JIRA_KEY} related changes"
    - "Search for existing E2E test code in current repository using grep/find for {JIRA_KEY}"
    - "Navigate to E2E repository directory or use current directory if tests are local"
    - "Build and verify test environment by running 'make all' to ensure everything is properly compiled"
    - "Create output directory: mkdir -p ../../test_artifacts/{COMPONENT}/{JIRA_KEY}/test_execution_results"
    - |
      MANDATORY: Execute actual test command: `./bin/extended-platform-tests run all --dry-run|grep "{JIRA_KEY}"|./bin/extended-platform-tests run --timeout 100m -f - --output-file ../../test_artifacts/{COMPONENT}/{JIRA_KEY}/test_execution_results/{JIRA_KEY}_test_execution_log.txt`
    - "CRITICAL: Wait for test execution to complete and capture real exit code"
    - "REQUIRED: Verify real log file exists with actual test output (not simulated content)"
    - "MANDATORY: If test failed with any errors (exit code != 0), MUST proceed to Test Result Analysis and Auto-Fix subtask"
    - "FORBIDDEN: Skipping auto-fix workflow for any test failure type"

    # STEP 3: Test Result Analysis + Auto-Fix after test execution + Re-execute test with corrections 
    - "MANDATORY: Analyze the test execution log file for specific error messages"
    - "Use DeepWiki MCP to analyze correct command syntax and patterns for the specific failure"
    - "INTELLIGENT ERROR ANALYSIS: Extract all error messages, stack traces, and failure points from logs"
    - "Analyze error messages and determine root causes with HIERARCHICAL classification"
    - "EXECUTION PATHS: IF CLASSIFIED AS E2E CODE/CONFIG ISSUE → Attempt auto-fix; IF CLASSIFIED AS PRODUCT BUG → Create bug report"
    - "MANDATORY: Apply corrections to the test code files and re-execute test with corrections"
    - "REQUIRED: Update test report with auto-fix attempts, classification, and results"

    # STEP 4: Update Test Coverage Matrix
    - "MANDATORY: Read test_artifacts/{COMPONENT}/{JIRA_KEY}/test_coverage_matrix.md"
    - "MANDATORY: Parse test execution log to extract test results for each Test Case ID"
    - "MANDATORY: Update Status column in test_coverage_matrix.md based on execution results:"
    - "  ✅ Passed - Test executed successfully (exit code 0, no failures)"
    - "  ❌ Failed - Test executed but failed (exit code != 0, test failures)"
    - "  ⚠️ Skipped - Test not executed (not found in execution log)"
    - "  🔄 Retried - Test failed initially but passed after auto-fix"
    - "  🐛 Product Bug - Test failed due to product defect (not test issue)"
    - "MANDATORY: Calculate coverage metrics:"
    - "  - Total scenarios defined in matrix"
    - "  - Scenarios executed (Passed + Failed + Retried + Product Bug)"
    - "  - Scenarios not executed (Skipped)"
    - "  - Pass rate = (Passed + Retried) / Executed * 100%"
    - "  - Execution coverage = Executed / Total * 100%"
    - "MANDATORY: Write updated test_coverage_matrix.md with new status values"
    - "MANDATORY: Add coverage summary section at the end of matrix file"

input:
  required:
    - name: "jira_issue_key"
      type: "string"
      description: "JIRA issue key for test execution"
      example: "HIVE-2883"
    - name: "component"
      type: "string"
      description: "Target component (e.g., hive, cco, other)"
      example: "hive"
  optional:
    - name: "e2e_test_results_input"
      type: "file"
      description: "E2E test generation results (if available)"
      path: "test_artifacts/{COMPONENT}/{JIRA_KEY}/phases/{JIRA_KEY}_e2e_test_results.md"

output:
  files:
    - name: "test_coverage_matrix.md"
      path: "../../test_artifacts/{COMPONENT}/{JIRA_KEY}/test_coverage_matrix.md"
      format: "markdown"
      description: "UPDATED test coverage matrix with execution status and coverage metrics"
      update_behavior: "Read existing file, update Status column, add Coverage Summary section"
      status_values:
        - "✅ Passed - Test executed successfully"
        - "❌ Failed - Test executed but failed"
        - "⚠️ Skipped - Test not executed"
        - "🔄 Retried - Failed initially, passed after auto-fix"
        - "🐛 Product Bug - Failed due to product defect"
      coverage_metrics:
        - "Total Scenarios"
        - "Scenarios Executed"
        - "Scenarios Skipped"
        - "Pass Rate (%)"
        - "Execution Coverage (%)"
    
    - name: "{JIRA_KEY}_test_execution_log.txt"
      path: "../../test_artifacts/{COMPONENT}/{JIRA_KEY}/test_execution_results/{JIRA_KEY}_test_execution_log.txt"
      format: "text"
      description: "Raw test execution log from extended-platform-tests command output"
    
    - name: "{JIRA_KEY}_comprehensive_test_results.md"
      path: "../../test_artifacts/{COMPONENT}/{JIRA_KEY}/test_execution_results/{JIRA_KEY}_comprehensive_test_results.md"
      format: "markdown"
      description: "Detailed test execution results with per-scenario analysis"
      must_include:
        - "Test execution summary for each scenario"
        - "Error messages and stack traces (if failed)"
        - "Auto-fix attempts and results (if applicable)"
        - "Product bug classification (if applicable)"
    
    - name: "{JIRA_KEY}_product_bug_report.md"
      path: "../../test_artifacts/{COMPONENT}/{JIRA_KEY}/test_execution_results/{JIRA_KEY}_product_bug_report.md"
      format: "markdown"
      description: "Product bug report generated when test failure analysis reveals actual product defects"
      condition: "Created only when failure analysis determines root cause is a product bug"

tools:
  - name: "Bash"
    description: "Execute shell commands for environment validation and test execution"
  - name: "DeepWiki MCP"
    description: "Analyze correct command syntax and component patterns"
  - name: "File operations"
    description: "Read configuration files and write execution results"
  - name: "WebFetch"
    description: "Fetch additional context if needed"

configuration:
  dynamic_variables:
    - "{COMPONENT}"
    - "{JIRA_KEY}"
  template_replacement: true
  template_enforcement: "strict"

  performance_optimization:
    target_execution_time: "60-90 minutes"
    balance: "Quality over speed - comprehensive test execution with validation"
    critical_performance_rules:
      parallel_execution_mandatory:
        - "Execute environment validation steps in parallel where possible"
        - "Parallel log analysis for error classification"
      fast_mode_default:
        - "Streamlined error analysis for common failure patterns"
        - "Prioritize critical test execution paths"
      execution_strategies:
        - "Execute environment checks first, then test execution"
        - "Mandatory auto-fix workflow for any test failure"
        - "Comprehensive report generation with coverage analysis"
    performance_targets:
      - "Step 1 (Environment): 5-10 seconds"
      - "Step 2 (Test Execution): 30-60 minutes"
      - "Step 3 (Analysis/Auto-fix): 10-20 minutes"
      - "Step 4 (Report): 5 minutes"
    output_efficiency:
      - "Generate comprehensive reports with detailed analysis"
      - "Include auto-fix attempts and classification details"
      - "Document technical barriers and recommendations"

content_limits:
  maximum_size: "20KB"
  style_guidelines:
    - "Execute all test phases directly without calling other agents"
    - "Focus on comprehensive test execution and validation"
    - "Ensure all test execution phases complete successfully"
    - "Compile comprehensive test execution reports"
    - "Handle both manual and E2E test execution seamlessly"
