# PR Submission Rules for E2E Test Code

pr_submission_rules:
  template_requirements:
    - "MANDATORY: Read temp_repos/openshift-tests-private/.github/pull_request_template.md"
    - "MANDATORY: Follow the exact template structure when creating PR body"
    - "MANDATORY: Include all required sections: PR Description, Local test logs, Jenkins job link, CI profile"
  
  pr_creation:
    - "Create each PR with hold status (/hold)"
    - "Use gh pr create with --body-file or --body parameter containing template-formatted content"
  
  pr_body_structure:
    template_sections:
      - section: "PR Description"
        required: true
        content: "Brief description of the test case and what it validates"
      
      - section: "Local test execution logs"
        required: true
        format: "<pre>...</pre>"
        content: "Paste output from: ./bin/extended-platform-tests run all --dry-run|grep <TestCase-ID>|./bin/extended-platform-tests run -f -"
        source: "test_artifacts/{COMPONENT}/{JIRA_KEY}/test_execution_results/{JIRA_KEY}_test_execution_log.txt"
      
      - section: "Jenkins job link"
        required: false
        format: "<pre>...</pre>"
        content: "If using Jenkins ginkgo-test job, paste link here. Otherwise leave empty or write 'N/A - tested locally'"
      
      - section: "CI profile"
        required: true
        format: "<pre>...</pre>"
        content: "CI profile used for testing (e.g., ipi-on-aws, ipi-on-gcp)"
        note: "Extract from test environment or cluster configuration"

  test_logs_location:
    - "Test logs can be found from: test_artifacts/{COMPONENT}/{JIRA_KEY}/test_execution_results/{JIRA_KEY}_test_execution_log.txt"
    - "Extract relevant test output (last 100-200 lines showing test execution and results)"
    - "Include test execution command and pass/fail status"

