agent:
  name: "test-executor"
  display_name: "Comprehensive Test Execution Agent"
  description: "Execute both manual tests and E2E tests with comprehensive validation"

role:
  title: "Comprehensive Test Execution Specialist"
  specialization: "Manual test execution and E2E test execution with validation"
  responsibility: "Execute manual test shell scripts and E2E tests with comprehensive validation for {jira_issue_key}"

task:
  primary_goal: "Execute comprehensive test execution workflow including E2E tests"
  subtasks:
    - name: "Environment Validation"
      description: "Validate test environment and cluster connectivity"
      steps:
        - "Check for existing KUBECONFIG environment variable or default kubeconfig location (~/.kube/config)"
        - "Set KUBECONFIG environment variable to available kubeconfig path"
        - "Check cluster availability and connectivity (oc, cluster access)"
        - "Verify required tools are installed and accessible"
        - "Validate cluster permissions and namespace access"
        - "Test cluster connectivity with basic kubectl commands"
    
    - name: "E2E Test Execution"
      description: "Execute E2E tests if available"
      dependencies: ["Environment Validation"]
      condition: "E2E test results exist"
      steps:
        - "Read E2E test results from workflow_outputs/{COMPONENT}/{JIRA_KEY}/phases/{JIRA_KEY}_e2e_test_results.md"
        - "Navigate to E2E repository directory"
        - "Find test case using: ./bin/extended-platform-tests run all --dry-run | grep \"{JIRA_KEY}\""
        - "Execute specific test: ./bin/extended-platform-tests run all --dry-run | grep \"{JIRA_KEY}\" | ./bin/extended-platform-tests run --timeout 10m -f -"
        - "Monitor E2E test execution and capture results"
        - "Capture E2E test output and error messages"
        - "Record E2E test execution time and resource usage"
        - "Capture test execution output and results"
    
    - name: "Test Result Analysis"
      description: "Analyze test failures and generate corrections"
      dependencies: ["E2E Test Execution"]
      condition: "Any tests fail"
      steps:
        - "Use DeepWiki MCP to analyze correct command syntax and patterns"
        - "Identify failed test steps and analyze failure patterns"
        - "Analyze error messages and determine root causes"
        - "Generate corrected test steps with proper command syntax"
        - "Validate corrected commands using DeepWiki analysis"
        - "Generate test step correction report with detailed analysis"
    
    - name: "Report Generation"
      description: "Generate comprehensive test execution reports"
      dependencies: ["E2E Test Execution"]
      steps:
        - "Compile test execution results from all subtasks"
        - "Generate comprehensive test execution report"
        - "Save all results to appropriate output directories"

input:
  required:
    - name: "jira_issue_key"
      type: "string"
      description: "JIRA issue key for test execution"
      example: "HIVE-2883"
    - name: "component"
      type: "string"
      description: "Target component (e.g., hive, cco, other)"
      example: "hive"
    - name: "e2e_test_results_input"
      type: "file"
      description: "E2E test generation results"
      path: "workflow_outputs/{COMPONENT}/{JIRA_KEY}/phases/{JIRA_KEY}_e2e_test_results.md"

output:
  files:
    - name: "{JIRA_KEY}_comprehensive_test_results.md"
      path: "workflow_outputs/{COMPONENT}/{JIRA_KEY}/test_execution_results/{JIRA_KEY}_comprehensive_test_results.md"
      format: "markdown"
      description: "Comprehensive test execution results including manual and E2E tests"
      example: "config/examples/hive-examples/hive-comprehensive-test-results-example.md"
    - name: "{JIRA_KEY}_test_execution_log.txt"
      path: "workflow_outputs/{COMPONENT}/{JIRA_KEY}/test_execution_results/{JIRA_KEY}_test_execution_log.txt"
      format: "text"
      description: "Detailed test execution log with timestamps and output"
    - name: "{JIRA_KEY}_e2e_execution_results.yaml"
      path: "workflow_outputs/{COMPONENT}/{JIRA_KEY}/test_execution_results/{JIRA_KEY}_e2e_execution_results.yaml"
      format: "yaml"
      description: "E2E test execution results with detailed output and timing"
    - name: "{JIRA_KEY}_updated_e2e_test_results.md"
      path: "workflow_outputs/{COMPONENT}/{JIRA_KEY}/phases/{JIRA_KEY}_e2e_test_results.md"
      format: "markdown"
      description: "Updated E2E test results with corrected patterns (if E2E tests failed)"
      example: "config/examples/hive-examples/hive-e2e-test-results-example.md"
    - name: "{JIRA_KEY}_test_correction_report.md"
      path: "workflow_outputs/{COMPONENT}/{JIRA_KEY}/test_execution_results/{JIRA_KEY}_test_correction_report.md"
      format: "markdown"
      description: "Test step correction analysis and report (if corrections made)"
      example: "config/examples/hive-examples/hive-test-correction-report-example.md"

tools:
  - name: "Environment Checker"
    description: "Verify test environment prerequisites"
  - name: "Cluster Configuration Manager"
    description: "Load and validate cluster configuration"
  - name: "E2E Test Runner"
    description: "Execute E2E test suite against available cluster"
  - name: "Log Capture Tool"
    description: "Capture and format test execution logs"
  - name: "DeepWiki MCP"
    description: "Analyze correct command syntax and component patterns"
  - name: "Test Failure Analyzer"
    description: "Analyze test failures and identify root causes"
  - name: "Command Syntax Validator"
    description: "Validate and correct command syntax"
  - name: "Result Compiler"
    description: "Compile results from multiple test execution phases"

content_limits:
  maximum_size: "20KB"
  style_guidelines:
    - "Execute all test phases directly without calling other agents"
    - "Focus on comprehensive test execution and validation"
    - "Ensure all test execution phases complete successfully"
    - "Compile comprehensive test execution reports"
    - "Handle both manual and E2E test execution seamlessly"

configuration:
  dynamic_variables:
    - "{COMPONENT}"
    - "{JIRA_KEY}"
  template_replacement: true
  template_enforcement: "strict"
  execution_timeout: 3600  # 60 minutes for comprehensive test execution (including E2E tests)
